# Generated by Django 2.0.9 on 2019-02-07 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='website/static/images/projects')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(upload_to='profiles')),
                ('twitter_username', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Website'), (2, 'Design'), (3, 'Marketing'), (4, 'Social Media Campagin')], default=1)),
                ('client', models.CharField(max_length=255)),
                ('date_completed', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('tesimonial', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='website/static/media/projects')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.Project'),
        ),
    ]
