# Generated by Django 2.0.9 on 2019-02-07 05:18

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=s3direct.fields.S3DirectField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=s3direct.fields.S3DirectField(null=True),
        ),
    ]
