# Generated by Django 2.0.9 on 2019-02-08 23:53

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190208_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', s3direct.fields.S3DirectField(null=True)),
            ],
        ),
    ]
