# Generated by Django 2.0.9 on 2019-02-09 00:01

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
