# Generated by Django 2.0.9 on 2019-02-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190209_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, 'Development'), (2, 'Design'), (3, 'Social Media & Marketing'), (4, 'Visual Media')], default=1),
        ),
    ]
