# Generated by Django 2.0.9 on 2019-02-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190209_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fa_icon',
            field=models.CharField(blank=True, default='fas', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent_service',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Service'),
        ),
    ]
