# Generated by Django 2.0.9 on 2019-02-12 05:33

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190210_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
