# Generated by Django 2.0.9 on 2019-02-14 00:59

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='main_image',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='project',
            name='banner',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
