# Generated by Django 2.0.9 on 2019-02-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190214_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='client_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
