# Generated by Django 2.0.9 on 2019-02-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20190214_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='package',
            field=models.BooleanField(default=False),
        ),
    ]
