# Generated by Django 2.0.9 on 2019-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_service_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
