# Generated by Django 2.0.9 on 2019-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20190215_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
