# Generated by Django 2.0.9 on 2019-02-17 07:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_project_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
