# Generated by Django 2.0.9 on 2019-02-17 07:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190217_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
