# Generated by Django 2.0.9 on 2019-02-19 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20190219_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 23, 1, 59, 931483)),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 23, 1, 59, 932040)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 23, 1, 59, 929555)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 23, 1, 59, 930933)),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 23, 1, 59, 930233)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 23, 1, 59, 932475)),
        ),
    ]
