# Generated by Django 2.0.9 on 2019-02-19 23:12

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20190219_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
