# Generated by Django 2.0.9 on 2019-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20190219_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
