# Generated by Django 2.0.9 on 2019-02-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_instagrampost_instagram_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
