# Generated by Django 2.0.9 on 2019-03-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dev_mode',
            field=models.BooleanField(default=False),
        ),
    ]
