# Generated by Django 2.0.9 on 2019-03-03 07:16

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_profile_dev_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='large_avatar',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
