# Generated by Django 2.0.9 on 2019-03-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_project_large_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.AddField(
            model_name='service',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
