# Generated by Django 2.0.9 on 2019-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20190308_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='parent',
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('a', 'Parent'), ('b', 'Child'), ('c', 'Included'), ('d', 'Addon')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='fa_icon',
            field=models.CharField(blank=True, default='fas', max_length=255, null=True),
        ),
    ]
