# Generated by Django 2.0.9 on 2019-03-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20190308_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='parent_service',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'a'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('a', 'Parent'), ('b', 'Included'), ('c', 'Addon')], max_length=1, null=True),
        ),
    ]
