# Generated by Django 2.0.9 on 2019-03-12 05:06

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20190308_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'a'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Service'),
        ),
    ]
